### PR TITLE
Better selection in DatasetConfig

### LINKED ISSUE #386: Filters and subsection in data
Often we want to train on subsection of a dataset like excluding neutral current events or energy’s in a certain range. there should be a way to define simple cuts maybe in the dataset configs and maybe an option to give a path to a list of event_no for more complicated cuts.  is there a simple way to achieve the simple cuts in the current version of the training exaples?.

### PR DESCRIPTION
**Pull request by asogaard**
Adds:

* Ability to do a more comprehensive string-based selection in the `DatasetConfig` files, e.g. `event_no % 5 == 0 & abs(pid) == 12` which wasn't possible before. (The parser mistook `abs` for a variable, e.g.) 
* The option of combining multiple selections into a single, named dataset, see e.g.:

```yml
# dataset/config.yml
  selection:
      test:
          - 50000 random events ~ event_no % 5 == 0 & abs(pid) == 12
          - 50000 random events ~ event_no % 5 == 0 & abs(pid) == 14
          - 50000 random events ~ event_no % 5 == 0 & abs(pid) == 16
          - 50000 random events ~ event_no % 5 == 0 & abs(pid) == 13
          - 50000 random events ~ event_no % 5 == 0 & abs(pid) == 1
      validation:
          - 10000 random events ~ event_no % 5 == 1 & abs(pid) == 12
          - 10000 random events ~ event_no % 5 == 1 & abs(pid) == 14
          - 10000 random events ~ event_no % 5 == 1 & abs(pid) == 16
          - 10000 random events ~ event_no % 5 == 1 & abs(pid) == 13
          - 10000 random events ~ event_no % 5 == 1 & abs(pid) == 1
      train:
          - 10000 random events ~ event_no % 5 > 1 & abs(pid) == 12
          - 10000 random events ~ event_no % 5 > 1 & abs(pid) == 14
          - 10000 random events ~ event_no % 5 > 1 & abs(pid) == 16
          - 10000 random events ~ event_no % 5 > 1 & abs(pid) == 13
          - 10000 random events ~ event_no % 5 > 1 & abs(pid) == 1
```

* The option to load selection files (CSV, JSON) using the same syntax.

```yml
# dataset/config.yml
  selection:
      test: test_selection.csv
      train: 50000 random events ~ train_selection.csv
```

cc @moustholmes, @MortenHolmRep 

Closes #386

### CODE REVIEW

**Comment by asogaard** [comment]
Will try to create a few tests before converting into a genuine PR but let me know what you think in the meantime, @RasmusOrsoe, @moustholmes, and @MortenHolmRep!

**Comment by asogaard** [comment]
Alright, that's some additional unit tests added for the new functionality. Ready for your discerning eyes, @RasmusOrsoe.

**Comment by RasmusOrsoe** [comment]
@asogaard Hey! Really cool. All of this config stuff is very much new to me, and I caught myself thinking that if I'm not the only one thinking that, then perhaps a small introduction in one of our meetings might be useful..

Could you elaborate on

1. Can i still load in my diry csv files with selections in them?
2. How does the selection exist in the work flow? Is it stored on disk after the dataset is created first time? Or is the selection calculated every time you want the dataset?

**Comment by asogaard** [comment]
> @asogaard Hey! Really cool. All of this config stuff is very much new to me, and I caught myself thinking that if I'm not the only one thinking that, then perhaps a small introduction in one of our meetings might be useful..
> 
> Could you elaborate on
> 
> 1. Can i still load in my dirty csv files with selections in them?
> 2. How does the selection exist in the work flow? Is it stored on disk after the dataset is created first time? Or is the selection calculated every time you want the dataset?

1. Yes, I should have include that in the description above — but it's updated now. I'll also add a unit test of this.
2. It is saved as a temporary cache on disk (you can toggle whether to do this), but this is "hidden" from the user. So a JSON file with event numbers are calculated the first time you are resolving a string-based selection, and then saved as `/tmp/selection-<hash>.json`. This should remove a considerable overhead when running training scripts.

**Comment by RasmusOrsoe** [comment]
Really cool! Now you can tease me with uninformative dataset configs :-D

**Review by RasmusOrsoe — APPROVED** [review]

**Pull request merged**
