### PR TITLE
Fixed typos in docstrings

### PR DESCRIPTION
**Pull request by AMHermansen**
Fixed some minor typos in the docstring for a couple of functions in the dataset.py file

### CODE REVIEW

**Comment by AMHermansen** [comment]
It seems that there were some formatting errors in the file prior to this PR, should I also update the formatting, or do we leave it as is @RasmusOrsoe

**Comment by RasmusOrsoe** [comment]
Hey @AMHermansen. Thanks for correcting the typos! 

The code quality checks must pass. We did change between formats of doc strings some time ago, perhaps that is what caused this. In either case, it would be much appreciated if you would polish this such that the checks pass.

**Comment by AMHermansen** [comment]
Hello @RasmusOrsoe 

It seems that when I was correcting a typo I exceed the length limit in one of the descriptions, and I believe that descriptions are limited to a single line. Hence I've reworded the troubling line. While doing so I also noticed some more typos, which I've also corrected.

**Review by RasmusOrsoe — APPROVED** [review]
Very nice! Thanks @AMHermansen

**Pull request merged**
