### PR TITLE
SQLite utility methods

### LINKED ISSUE #358: Feature I3FeatureExtractorIceCube86 has issues when "pulse" is not in the name of the pulsemap
I am trying to convert a featuremap called `TWRTVetoSeries`, but I receive the error below, which is probably due to this :
```
def is_pulsemap_check(table_name: str) -> bool:
    """Check whether `table_name` corresponds to a pulsemap."""
    if "pulse" in table_name.lower():
        return True
    else:
        return False
```
So perhaps there is some other way to carry out the check, other than looking for "pulse" in the name. :-) 

```
 Traceback (most recent call last):
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1881, in _execute_context
    cursor, statement, parameters, context
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: TWRTVetoSeries.event_no

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "convert_i3_files_few.py", line 71, in <module>
    main_icecube86(backend)
  File "convert_i3_files_few.py", line 64, in main_icecube86
    converter.merge_files(os.path.join(outdir2, "dev_level7_{}_neutrinos.db".format(set_name)))
  File "/lustre/hpc/icecube/peter/workspace/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 104, in merge_files
    self._merge_temporary_databases(output_file, input_files)
  File "/lustre/hpc/icecube/peter/workspace/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 260, in _merge_temporary_databases
    self._submit_to_database(output_file, table_name, data)
  File "/lustre/hpc/icecube/peter/workspace/graphnet/src/graphnet/data/sqlite/sqlite_dataconverter.py", line 222, in _submit_to_database
    data.to_sql(key, engine, index=False, if_exists="append")
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1770, in to_sql
    **engine_kwargs,
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1350, in insert_records
    raise err
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 882, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1881, in _execute_context
    cursor, statement, parameters, context
  File "/groups/icecube/peter/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: TWRTVetoSeries.event_no
[SQL: INSERT INTO "TWRTVetoSeries" (charge, dom_time, dom_x, dom_y, dom_z, event_no, event_time, is_bad_dom, is_bright_dom, is_errata_dom, is_saturated_dom, pmt_area, rde, width) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ((0.875, 9458.0, -211.35000610351562, -404.4800109863281, 209.27000427246094, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (1.475000023841858, 9366.0, -211.35000610351562, -404.4800109863281, -335.3900146484375, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (0.7250000238418579, 6259.0, 405.8299865722656, -306.3800048828125, 120.68000030517578, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (1.225000023841858, 8208.0, -43.27000045776367, -267.5199890136719, -367.92999267578125, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (1.125, 7905.0, 544.0700073242188, 55.88999938964844, -92.94000244140625, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (0.925000011920929, 6798.0, 90.48999786376953, 82.3499984741211, -247.25, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (0.9750000238418579, 7686.0, 576.3699951171875, 170.9199981689453, 153.6300048828125, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (1.4249999523162842, 5894.0, 257.30999755859375, 211.66000366210938, 419.32000732421875, 808843, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0)  ... displaying 10 of 72969 total bound parameter sets ...  (0.9750000238418579, 8564.0, 41.599998474121094, 35.4900016784668, -157.89999389648438, 829903, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0), (0.7749999761581421, 6349.0, 106.94000244140625, 27.09000015258789, -223.83999633789062, 829903, 56783.915363512, -1, -1, -1, -1, 0.04439999908208847, -1.0, 8.0))]
(Background on this error at: https://sqlalche.me/e/14/gkpj) ```

### PR DESCRIPTION
**Pull request by asogaard**
* Removes duplication of `create_table` and `attach_index`-like functions
* Updates a call to `save_to_sql` in  [src/graphnet/data/utilities/parquet_to_sqlite.py](https://github.com/graphnet-team/graphnet/blob/main/src/graphnet/data/utilities/parquet_to_sqlite.py#L119-L138) that looked backwards to me. Please check whether I'm mistaken here, @RasmusOrsoe!

Closes #358 

cc @Peterandresen12

### CODE REVIEW

**Review by RasmusOrsoe — COMMENTED** [review]
Hey. I had a look here, and I can't by eye gauge if this works as intended. I would need to test these new changes to make sure everything works as intended.

Because `parquet_to_sqlite_converter` relies on these sqlite functions, which are also used by the `sqlite_data_converter`, we could end up in a situation where we change something based on usage of the `sqlite_data_converter` that breaks the `parquet_to_sqlite_converter`. So a unit test might be a good idea here.

**Comment by asogaard** [comment]
The functions that are used in `parquet_to_sqlite_converter` and `sqlite_data_converter` are virtually identical, which is why it would make sense to consolidate them and why I think the risk of introducing bugs is quite small. But I agree that unit tests are always healthy! I'll look into adding one — let me know if you have any concrete suggestions you'd like the test(s) to do. :)

**Comment by asogaard** [comment]
Alright, have added a unit test now, @RasmusOrsoe. The existing unit test converts a test I3-file using both `ParquetDataConverter` and `SQLiteDataConverter`. The new test then further converts the parquet output into a second SQLite database and compares this to the output of the `SQLiteDataConverter`. If this conversion works, and if the two databases look the same (i.e. have the same number of events, and identical feature tensors for each event) then we considering the code running as intended. :)

**Review by RasmusOrsoe — COMMENTED** [review]
Hey! I think this is great. 

Could we add a second test that checks that the tables are indexed correctly? I have a conceptual snippet here: 

```
def test_search_plan(sqlite_database, parquet_converted_database, pulsemap, event_no = 1):
    with sqlite3.connect(sqlite_database) as con:
        query = f'EXPLAIN QUERY PLAN SELECT * FROM {pulsemap} WHERE event_no={event_no}'
        sqlite_plan  = pd.read_sql(query,con)

    with sqlite3.connect(parquet_converted_database) as con:
        query = f'EXPLAIN QUERY PLAN SELECT * FROM {pulsemap} WHERE event_no={event_no}'
        parquet_plan  = pd.read_sql(query,con)
    
    assert 'USING INDEX event_no' in sqlite_plan['detail']
    assert 'USING INDEX event_no' in parquet_plan['detail']
    
    assert sqlite_plan['detail'] == parquet_plan['detail']

    return
```

Testing one `event_no` is enough pr. pulsemap

**Comment by asogaard** [comment]
There we go, @RasmusOrsoe: Have now added a unit test like the one suggested, and... **it actually caught a (seemingly ancient) bug!** 🎉     One place in the `SQLiteDataConverter`, the index wasn't being attached to the pulse map table. I have added a `create_table_and_save_to_sql` function that automatically creates a table being saved to if it doesn't already exist.

**Pull request merged**
