### PR TITLE
Load multiple parquet files

### PR DESCRIPTION
**Pull request by The-Ludwig**
Talked with @RasmusOrsoe and loading in multiple parquet files with `ParquetDataset` was not supported. It is fairly simple to implement that with awkward, this PR should to the trick.

### CODE REVIEW

**Comment by The-Ludwig** [comment]
@MortenHolmRep Done! :)

**Review by MortenHolmRep — APPROVED** [review]
Look good @The-Ludwig ! Thanks for the quick fix and PR.

**Comment by MortenHolmRep** [comment]
@The-Ludwig Feel free to merge it when you're ready ;)

**Comment by The-Ludwig** [comment]
> @The-Ludwig Feel free to merge it when you're ready ;)

I am not allowed to merge, sadly. (I like to hit the button ;) )

**Comment by MortenHolmRep** [comment]
> > @The-Ludwig Feel free to merge it when you're ready ;)
> 
> I am not allowed to merge, sadly. (I like to hit the button ;) )

My bad! I'll merge it 🙂

**Pull request merged**
